manageBestFilm()
manageTopRatedFilms()
manageTopRatedFilmsByGenre("Horror", "#film-category-one")
manageTopRatedFilmsByGenre("Sci-Fi", "#film-category-two")
manageUserChoiceGenre()
manageModalWindow()
responsiveControls()